[package]
name = "cooklang-reports"
version = "0.1.0"
edition = "2024"

[dependencies]
cooklang = "0.15"
minijinja = "2.8"
serde = { version = "1.0", features = ["derive"] }
yaml-datastore = { path = "../yaml-datastore" }
indoc = "2.0"

[dev-dependencies]
indoc = "2.0"
